version: "3.9"

services:
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 5s
      retries: 15

  server1:
    build: ./server
    container_name: socketio-server1
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  server2:
    build: ./server
    container_name: socketio-server2
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy

  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    ports:
      - "8080:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - server1
      - server2
