version: "3.9"

services:
  redis:
    image: redis:7.4.1-alpine
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 5s
      retries: 15

  server:
    build: ./server
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy


  caddy:
    image: caddy:2.10.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - server
